name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute VITE_BASE (user page vs project page)
        shell: bash
        run: |
          REPO="${{ github.event.repository.name }}"
          if [[ "$REPO" == *.github.io ]]; then
            echo "VITE_BASE=/" >> $GITHUB_ENV
          else
            echo "VITE_BASE=/$REPO/" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Generate heroList.json
        run: node scripts/generateHeroList.js

      - name: Build
        run: npm run build

      - name: List dist contents (diagnostic)
        run: |
          echo "VITE_BASE=$VITE_BASE"
          echo "--- DIST TREE ---"
          ls -l dist || true
          echo "--- DIST ROOT FILES ---"
          ls -l dist | sed -n '1,200p' || true
          echo "--- Find equipmentData.json ---"
          find dist -maxdepth 2 -iname 'equipmentData.json' -print || echo "equipmentData.json NOT FOUND in dist"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
